### ISSUE TITLE
Add a search feature to a homepage

### ISSUE THREAD

**Issue by codewithhermes** [codewithhermes/Job-Searching-Web-App#1]
***Feature Request: Add Job Post Search by Keyword***

Description:

We need to implement a feature that allows users to search for job posts using keywords. The feature will be accessible through a GET request and will return a list of job posts that match the given keyword.

**Details:**
The endpoint will take a path variable {keyword}, which represents the search term.
The controller method will call the service layer to fetch job posts that contain the keyword in their title, description, or other relevant fields.
The service method search(String keyword) should handle the actual search logic.
The response will be a list of job posts (List<JobPost>) that match the search term.

**Acceptance Criteria:**

 The endpoint should accept a keyword as a path variable.
 It should return a list of job posts that match the given keyword.
 Proper error handling should be implemented for cases where no job posts are found.
 Unit tests should be provided to verify the functionality.

**Path to the file**
[Job-Searching-Web-App](https://github.com/codewithhermes/Job-Searching-Web-App/tree/main)/[Job Searching Portal]

**Comment by ayush1233** [comment]
I want to contribute on this issue

**Comment by codewithhermes** [comment]
are you familiar with springboot?

**Comment by ayush1233** [comment]
Yes

**Comment by ArshKumar84** [comment]
I want to contribute on the issue, I have been working on REST APIs using spring boot

**Comment by ArshKumar84** [comment]
Is the requirement is to find the jobPost using postProfile (field in JobPost.java) as a keyword 
![image](https://github.com/user-attachments/assets/e424aabc-18f9-4a58-8723-e93c9857e6dc)

**Comment by SandikaDassanayake** [comment]
Dear Maintainers,

I have reviewed Issue #1 regarding the addition of a search feature to the homepage. I am interested in contributing to this enhancement.

My Proposed Approach:

Endpoint Implementation: Develop a GET endpoint that accepts a {keyword} as a path variable.
Controller Update: Modify the controller to call the service layer for searching job posts.
Service Layer Development: Implement the search(String keyword) method to handle the search logic, querying job posts based on the keyword in titles, descriptions, or relevant fields.
Error Handling: Include proper error handling for cases where no job posts are found.
Unit Testing: Write unit tests to ensure the functionality works as expected.
Please let me know if I can proceed with this issue.

Best regards
