### ISSUE TITLE
Adding job feature

### ISSUE THREAD

**Issue by codewithhermes** [codewithhermes/Job-Searching-Web-App#3]
**Feature Request: Add Job Posting Functionality**
Feature Overview:
The goal is to implement a feature that allows users to add job postings via a REST API. This will enable job creation and retrieval of specific job posts based on their postId.

**Implementation Details:**
Create a POST endpoint (/jobPost) to handle job postings.
The API should accept a JobPost object in the request body and store it using the service layer.
After saving the job post, the service will return the saved job post based on its unique postId.
Proposed Solution:
The feature should be implemented as follows:

Controller:

Add a new @PostMapping method to handle job creation.
Accept a JobPost object in the request body.
Use the service to add the job and retrieve it using postId

**issue from  JobRestController.java file**

**Comment by ayush1233** [comment]
i want to solve this issue
