### ISSUE TITLE
add Lombok dependency  to pom.xml

### ISSUE THREAD

**Issue by codewithhermes** [codewithhermes/Job-Searching-Web-App#5]
**Issue: Add Lombok Dependency and Refactor JobPost Class**
Feature Overview:
We need to simplify the JobPost class by reducing boilerplate code using the Lombok library. Lombok will auto-generate common methods like getters, setters, constructors, etc. This will streamline the code and enhance maintainability.

Implementation Details:
Add Lombok Dependency:

Update the pom.xml to include the Lombok dependency

**Comment by ashutoshsarap** [comment]
I have used Lombok in previous projects. I can contribute in solving this issue
