### ISSUE TITLE
update job post feature

### ISSUE THREAD

**Issue by codewithhermes** [codewithhermes/Job-Searching-Web-App#6]
Issue: Update Job Post Feature in JobRestController.java
Feature Overview:
The objective is to implement a feature to update an existing job post using a PUT request in the JobRestController.java. This feature will allow users to modify the details of an existing job post based on its unique postId.

Implementation Details:
Map Update Job Post Endpoint in JobRestController:

Add a new @PutMapping method to handle updating an existing job post.
The endpoint should accept a JobPost object in the request body and the postId as a path variable to identify the job post to update.

**Comment by ashutoshsarap** [comment]
I have expertise in solving this issue, I can optimize the solution
