### ISSUE TITLE
 Implement Feature to List All Job Posts 

### ISSUE THREAD

**Issue by codewithhermes** [codewithhermes/Job-Searching-Web-App#8]
Issue: Implement Feature to List All Job Posts in JobService.java
Feature Overview:
The goal of this feature is to allow users to retrieve a list of all job posts in the system. A new method will be implemented in the service layer to return all job posts from the database.

Implementation Details:
Add Get All Jobs Method in JobService:

Implement a method getAllJobs() in JobService.java that retrieves all job posts using the repository.
The method will interact with the JobRepository to fetch all records from the JobPost table.

**Comment by ArshKumar84** [comment]
I have made a pull request and solved this issue

**Comment by ashutoshsarap** [comment]
Assign this to me

**Comment by ArshKumar84** [comment]
The pull request for this issue has been merged but the issue isn't closed yet
Update JobService.java #12
